### ISSUE TITLE
Sample scripts out of date for v0.5.0

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath-docs#105]
See https://www.youtube.com/watch?v=Ou5qqHK5NV8

Specifically the `Dialogs` class has moved!

**Comment by alanocallaghan** [comment]
Should we also move and update the advice on scripting setups? Currently the intellij setup is on the wiki only, and I could add vscode instructions

**Comment by petebankhead** [comment]
Yes please!

**Comment by alanocallaghan** [comment]
The only mention of Dialogs is in the StarDist section (https://github.com/search?q=repo%3Aqupath%2Fqupath-docs%20Dialogs&type=code), and it doesn't specify where the import is from.

Reviewing the video, the import error is from `import static qupath.lib.gui.scripting.QPEx.` and `import static qupath.lib.gui.scripting.QPEx`, which aren't valid imports; the one in the docs is `import static qupath.lib.gui.scripting.QPEx.*`.

Having said that, draft of improved scripting instructions: #113
