### ISSUE TITLE
typos in scripting section

### ISSUE THREAD

**Issue by f--f** [qupath/qupath-docs#2]
Hi, I just noticed two errors when browsing the documentation in this section: https://qupath.readthedocs.io/en/latest/docs/scripting/overview.html#working-with-bufferedimages

- First code block is not closed properly (indentation issue)
- `BufferedImage.TYPE*BYTE*GRAY` should instead be `BufferedImage.TYPE_BYTE_GRAY`

**Comment by petebankhead** [comment]
Thanks, fixed now.
