### ISSUE TITLE
Update link to jdk download source

### ISSUE THREAD

**Issue by jo-mueller** [qupath/qupath-docs#44]
I just noticed that the archive page cited in the build reference (https://adoptopenjdk.net/) has moved to a different page:

![screenshot](https://user-images.githubusercontent.com/38459088/184649530-29c67e36-55f0-4e18-8464-40b48e58ae53.PNG)

The new link is https://adoptium.net/temurin/releases

**Comment by petebankhead** [comment]
Fixed by https://github.com/qupath/qupath-docs/pull/46 - so the link should be ok for QuPath v0.4.0, or at https://qupath.readthedocs.io/en/latest/
